version: "3"
services:
  node0:
    build: .
    image: network
    container_name: node0
    networks:
      myapp:
        ipv4_address: 172.28.5.1

  node1:
    build: .
    image: network
    container_name: node1
    networks:
      myapp:
        ipv4_address: 172.28.5.2

  node2:
    build: .
    image: network
    container_name: node2
    networks:
      myapp:
        ipv4_address: 172.28.5.3

  node3:
    build: .
    image: network
    container_name: node3
    networks:
      myapp:
        ipv4_address: 172.28.5.4

networks:
  myapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.5.0/16
