version: '3'
services:

  node0:
    build: .
    image: network
    container_name: node0
    networks:
      myapp:
        ipv4_address: 127.0.0.1

  node1:
    build: .
    image: network
    container_name: node1
    networks:
      myapp:
        ipv4_address: 127.0.0.1

  node2:
    build: .
    image: network
    container_name: node2
    networks:
      myapp:
        ipv4_address: 127.0.0.1

  node3:
    build: .
    image: network
    container_name: node3
    networks:
      myapp:
        ipv4_address: 127.0.0.1

networks:
  myapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24